apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - image: franckcussac/consumer
        name: consumer
        env:
        - name: BROKER
          value: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local:9092
        - name: TOPIC
          value: test
        - name: GROUP_ID
          value: app_1
